spring.application.name=Employee-app3

spring.datasource.url=your_path
spring.datasource.username=your_name
spring.datasource.password=your_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
